### ISSUE TITLE
插件很赞👍

### ISSUE THREAD

**Issue by chu-shen** [zhy201810576/ETagConverter#1]
刚搜插件才发现这好东西，开箱即用，很赞👍

---

分享一下：

如果要自动替换新入库的同人志，可以试下「Admin Settings」的「Tag Rules」

直接把文本复制进去就行👉https://github.com/chu-shen/LANraragi-scripts/blob/main/tags-20230428.txt

**Comment by zhy201810576** [comment]
谢谢你对我插件的认可，能够帮助到你是我的荣幸😊
