### ISSUE TITLE
插件加入仓库使用请求

### ISSUE THREAD

**Issue by WindyCloudCute** [zhy201810576/ETagConverter#2]
你好,我是负责LANraragi_CN项目的后续的汉化,想询问以下这边,可不可以允许我将插件加入后续的LANraragi_Chinese构建发布?

**Comment by zhy201810576** [comment]
你好，`LANraragi_CN`项目的负责人。我很荣幸可以将插件[ETagConverter](https://github.com/zhy201810576/ETagConverter)加入到你项目的后续构建发布，希望我的插件可以为你的项目增添点微薄的贡献😀

**Comment by WindyCloudCute** [comment]
很开心您同意了,也谢谢您的支持。
